// RPNCalcClient.cpp : This file contains the 'main' function. Program execution begins and ends there.
//
// 
//#include <initguid.h>
#include <Windows.h>
#include <stdio.h>

//#include <cguid.h>

#include <atlcomcli.h>

#include <iostream>

// in-process dll example
//#include "..\RPNCalculator\RPNCalcInterfaces.h"

// comes from files generated by idl file
#include "..\RPNCalculator-out-of-proc-server\CalculatorTypeInfo.h"
#include "..\RPNCalculator-out-of-proc-server\CalculatorTypeInfo_i.c"

int main()
{
    auto hr = CoInitialize(NULL);

    CComPtr<IRPNCalculator> spCalc;
    //hr = spCalc.CoCreateInstance(__uuidof(RPNCalculator));
    hr = spCalc.CoCreateInstance(CLSID_RPNCalculator);
    if (FAILED(hr)) {
        std::cout << "last error" << (LPVOID)hr << "\n";
        return -1;
    }
        

    spCalc->push(10);
    spCalc->push(6);
    spCalc->push(12);
    spCalc->add();

    double result;
    spCalc->pop(&result);
    printf("value poped: %lf\n", result);

    spCalc->push(result);
    spCalc->subtract();
    spCalc->pop(&result);
    printf("value poped: %lf\n", result);

    CoUninitialize();

    return 0;
}

// Run program: Ctrl + F5 or Debug > Start Without Debugging menu
// Debug program: F5 or Debug > Start Debugging menu

// Tips for Getting Started: 
//   1. Use the Solution Explorer window to add/manage files
//   2. Use the Team Explorer window to connect to source control
//   3. Use the Output window to see build output and other messages
//   4. Use the Error List window to view errors
//   5. Go to Project > Add New Item to create new code files, or Project > Add Existing Item to add existing code files to the project
//   6. In the future, to open this project again, go to File > Open > Project and select the .sln file
